Vagrant.configure("2") do |config|

  config.vm.box = "gozma14/wp"
  config.vm.hostname = "gaboo-piwik"
  config.vm.network "private_network", ip: "192.168.27.14"
  config.vm.synced_folder "..", "/vagrant"

  ###############################################################
  # gaboo synced folders
  ###############################################################

  config.vm.synced_folder "../gaboo/gaboo", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo"
  config.vm.synced_folder "../gaboo/gaboo-core", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-core"
  config.vm.synced_folder "../gaboo/gaboo-lock", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-lock"

  ###############################################################
  # gaboo-piwik synced folders
  ###############################################################

  config.vm.synced_folder "../gaboo-piwik", "/var/www/www.192.168.27.14.xip.io/public_html/wp-content/plugins/gaboo-piwik"

  ###############################################################
  # cli/provision
  ###############################################################

  config.vm.provision "shell", path: "cli/provision.sh", privileged: false

end